version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "19:00"
  open-pull-requests-limit: 10
- package-ecosystem: composer
  directory: "/vendor-bin/dev"
  schedule:
    interval: daily
    time: "19:00"
  open-pull-requests-limit: 10
